server:
    websocket:
        port: 9873
    tcp:
        port: 9872
    # noGroupAction specifies if a client that subscribes without specifying a
    # group gets all messages or none. This flag can be specified as 'all' or
    # 'none'
    noGroupAction: "none"
logging:
    level: "debug"
